config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  get '/home' => 'users#index'
  get '/login' => 'users#login'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#signup'
  post '/signup' => 'users#create'
  delete '/logout' => 'users#destroy'
  resources :users, only: [:index, :show, :new, :create, :edit, :update, :delete]
  resources :books, only: [:index, :show, :new, :create, :edit, :update, :delete]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/auth/google_oauth2/callback' => 'sessions#google'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    validates :description, :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    # has_secure_password
    has_many :books
    validates :email, uniqueness: true
    validates :username, uniqueness: true
    # validates :username, :password, presence: true

    # validates :title, presence: true;
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    helper_method :current_user, :logged_in? 

    private

    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!session[:user_id]
    end

    def redirect_if_not_logged_in
        redirect_to '/' if !logged_in?
    end


    protect_from_forgery with: :exception
   
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :redirect_if_not_logged_in

    def index
        if params[:q]
            @books = Book.search(params[:q])
        else
            @books = Book.alpha.all
        end
    end

    def show
        @book = Book.find_by_id(params[:id])
    end

    def new
        @book = Book.new
    end

    def create
        @book = current_user.books.build(recipe_params)
        if @book.save
            redirect_to book_path(@book)
        else
            render :new
        end
    end

    def edit
        @book = Book.find(params[:id])
    end

    def update
        @book = current_user.books.find(params[:id])
     
        if @book.update(book_params)
            redirect_to book_path(@book)
        else
            @error = @book.errors.full_messages
            render :edit
        end
    end

    private

    def book_params 
        params.require(:book).permit(:title, :author, :genre, :pages, :description)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def index
        @user = User.find_by_id(params[:id])
    end

    def create
        @user = User.find_by_id(params[:id])
        if @user && @user.authenticate(params[:user][:password])
            session[:user_id] = @user.id 
            redirect_to user_path(@user) 
        else
            flash[:message] = "Incorrect login information"
            redirect_to '/login'
        end
    end

    # def google
    #     @user = User.find_or_create_by(email: auth["info"]["email"]) do |user|
    #         user.user_name = auth["info"]["first_name"]
    #         user.password = SecureRandom.hex(10)
    #     end
    #     if @user.save
    #         session[:user_id] = @user.id 
    #         redirect_to user_path(@user)
    #     else
    #         redirect_to '/'
    #     end
    # end

    # def destroy
    #     session.delete :user_id
    #     redirect_to root_path
    # end
    

    private

    def auth
        request.env['omniauth.auth']
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        @user = User.find_by_id(params[:id]) 
    end

    def show
        redirect_if_not_logged_in
        @user = User.find_by_id(params[:id])
        redirect_to '/' if !@user
    end
    
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        
        if @user.save
            session[:user_id] = @user.id 
            redirect_to @user
        else
            @error = @user.errors.full_messages.to_sentence
            render :signup
        end
    end

    # def show
    #     redirect_if_not_logged_in
    #     @user = User.find_by_id(params[:id])
    #     redirect_to '/' if !@user
    # end

    def destroy
        session.delete :user_id
        redirect_to root_path
    end

    private

    def user_params
        params.require(:user).permit(:username, :email)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb
<div>
  <h4>Search for a Book: </h4>
  <%= form_tag(books_path, method: 'get') do %>
    <%= text_field_tag(:q) %>
    <%= submit_tag("search") %>
  <% end %>
</div>


<div>
    <ul>
      <% @books.each do |book| %>
        <li><%= link_to book.title, book_path(book) %></li>
      <% end %>
    </ul> 
</div> 

app/views/layouts/_nav.html.erb
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <style>
        .w3-bar-block .w3-bar-item {
            padding: 20px
        }
    </style>

    <% if logged_in? %>
        <nav class="w3-sidebar w3-bar-block w3-card w3-top w3-xlarge w3-animate-left" style="display:none;z-index:2;width:40%;min-width:300px" id="mySidebar">
            <%= link_to 'Books', recipes_path, onclick: "w3_close()", class: "w3-bar-item w3-button" %>
            <%= link_to 'Add a Book', new_recipe_path, onclick: "w3_close()", class: "w3-bar-item w3-button" %>
            <%= button_to 'Logout', logout_path, method: "delete", onclick: "w3_close()", class: "w3-bar-item w3-button" %>

            <a href="javascript:void(0)" onclick="w3_close()" class="w3-bar-item w3-button">Close Menu</a>

        </nav>


        <div class="w3-top">
            <div class="w3-white w3-xlarge" style="max-width:1200px;margin:auto">
                <div class="w3-button w3-padding-16 w3-left" onclick="w3_open()">☰</div>
                <div class="w3-center w3-padding-16"><%= link_to 'MyRecipes', root_path %></div>
            </div>
        </div>
    <% end %>


    <% if !logged_in? %>
        <div class="w3-top">
            <div class="w3-white w3-xlarge" style="max-width:1200px;margin:auto">
                <div class="w3-button w3-padding-16 w3-left" onclick="w3_open()">☰</div>
                <nav class="w3-sidebar w3-bar-block w3-card w3-top w3-xlarge w3-animate-left" style="display:none;z-index:2;width:40%;min-width:300px" id="mySidebar">
                    <%= link_to 'Login', login_path, onclick: "w3_close()", class: "w3-bar-item w3-button" %>
                    <%= link_to 'Signup', signup_path, onclick: "w3_close()", class: "w3-bar-item w3-button" %>
                    <%= link_to 'HOME', home_path, method: 'get' %>

                    <a href="javascript:void(0)" onclick="w3_close()" class="w3-bar-item w3-button">Close Menu</a>
                </nav>
                <div class="w3-center w3-padding-16"><%= link_to 'MyRecipes', root_path %></div>
            </div>
        </div>
    <% end %>

    <script>
        function w3_open() {
            document.getElementById("mySidebar").style.display = "block";
        }

        function w3_close() {
            document.getElementById("mySidebar").style.display = "none";
        }
    </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        
        <meta charset="utf-8"/>
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>BookWorks</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"/>
        <link rel="stylesheet" type="text/css" href="../app/stylesheets/styles.css"/>
        <script src="https://kit.fontawesome.com/bc519c4149.js" crossorigin="anonymous"></script>

    </head>

    <body>
        <header>
            <%# <%= render 'layouts/nav' %>
        </header>

    <div class="app-container">


    <nav class="navbar navbar-dark bg-dark">

        <div class="top-bar-title">
            <div class="topbar-responsive-logo">
                <strong><i class="fas fa-book-reader"></i>&emsp;BOOKWORMS</strong>
            </div>
        </div>

        <ul class="nav nav-pills justify-content-end">
            <li class="nav-item btn btn-outline-light btn-lg">
                <%= link_to 'LOGIN', login_path, method: 'get' %>
            </li>
                &emsp;

            <li class="nav-item btn btn-outline-light btn-lg">
                <%= link_to 'SIGNUP', signup_path, method: 'get' %>
            </li>
            &emsp;

        <li class="nav-item btn btn-outline-light btn-lg">
            <%= link_to 'HOME', home_path, method: 'get' %>
        </li>

        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </li>

    </ul>
</nav>


        

        <div>
            <% if flash[:message] %>
                <%= flash[:message] %>
            <% end %>
            <%= @error %>
        </div>

        <main role="main">
            <%= content_for?(:content) ? yield(:content) : yield %>
        </main>

        <nav class="navbar fixed-bottom navbar-expand-lg navbar-dark bg-dark">
            <div class="container justify-content-end">

                <div class="bottombar-responsive-logo">
                <strong><i class="fas fa-book-reader"></i>&emsp;&copy; 2020 Fans Top Sites</strong></div>
            </div>
        </nav>


    </body>
</html>

app/views/layouts/books.html.erb
<% content_for :content do %>
 <div class="jumbotron text-center">
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <p>
                    <%= yield %>
                </p>
            </div>
           
        </div>
    </div>
<% end %>

app/views/users/index.html.erb
<div class="col-md-12 text-center">
<% if logged_in? %>
    <h1>Welcome Again!</h1>
    <h4>Lets get started.. View all Books or Add a new Book!!</h4>
    <br>
    <%= button_to "Books", books_path, method: 'get' %>
    <br>
    <%= button_to 'Add a Book', new_book_path, method: 'get' %>
    <br>
    <%= button_to 'LOGOUT', logout_path, method: "delete" %>
<% else %>
   <h1>Welcome to Bookworms</h1>
   <h4>Create, Read, Update, and Delete your Favorite Books!</h4>
<% end %>
<br>

<%= image_tag 'https://i2-prod.walesonline.co.uk/incoming/article8624804.ece/ALTERNATES/s1227b/Theology-Room-3.jpg', class: 'welcome-img'%>
<%# <%= button_to 'LOGOUT', logout_path, method: "delete" %> %>


</div>

app/views/users/login.html.erb
<div class="col-md-12 text-center">
<h1>Login</h1>

<%= flash[:message] if flash[:message]%>
<br></br>

<%= form_for :user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <br>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>
    <br>
    <%= f.submit "Login" %>
<% end %>
<br>
<%= link_to "Sign Up Here", signup_path %>
<br>
<%=image_tag 'https://www.wendywutours.co.uk/blog/wp-content/uploads/2017/11/8booksheader-730x410.jpg', class: 'login-img'%>





</div>

app/views/users/show.html.erb
<div class="col-md-12 text-center">
<br><br>
<h1>Welcome, <%= @user.username %>!</h1>
<h4>Add a new book or view all books.</h4>
<br>
<%= button_to "Books", books_path, method: 'get' %>
<br>
<%= button_to 'Add a Book', new_book_path %>
<br>


<%= image_tag 'https://media.istockphoto.com/photos/education-concept-with-book-in-library-picture-id944631208?k=6&m=944631208&s=612x612&w=0&h=5Hx0ksAT5Majaz40Iov6oLO6GaDn2cxySnNTDTH3Qk8=', class: 'book-img'%>
</div>

app/views/users/signup.html.erb
<div class="col-md-12 text-center">


<h1>Sign Up</h1>

<br></br>

<%= form_for :user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <br>
    <br>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <br>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>
    <br>
    <%= f.submit "Submit" %>
<% end %>
<br> 

<%=image_tag 'https://blog.directenergy.com/wp-content/uploads/2016/05/OpenBookLibraryHeader-717x300.jpg', class: 'signup-img'%>




</div>